apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  namespace: t
  labels:
    app: be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: poc
        image: kuberegistry0.azurecr.io/t.poc:v3.4
        command: ["/go/bin/backend"]
        args: ["-j", "JOB-QUEUE-V3-1", "-q", "bootstrap.kafka.svc.cluster.local:9092", "-w", "wk-%d.wk.t.svc.cluster.local:4002", "-n", "3" ]
        resources:
          requests:
            cpu: "3"
            memory: "4Gi"
