apiVersion: v1
kind: Service
metadata:
  name: fe
  namespace: t
  labels:
    app: fe
spec:
  ports:
  - port: 4001
    targetPort: 4001
  selector:
    app: fe
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  namespace: t
  labels:
    app: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: poc
        image: kuberegistry0.azurecr.io/t.poc:v3.4
        command: ["/go/bin/frontend"]
        args: ["-j", "JOB-QUEUE-V3-1", "-q", "bootstrap.kafka.svc.cluster.local:9092", "-p", "4001"]
        ports:
        - containerPort: 4001
        resources:
          requests:
            cpu: "3" 
            memory: "12Gi"        

        
