---
apiVersion: v1
kind: Pod
metadata:
  name: bench
  labels:
    app: bench
spec:
  containers:
  - name: bench
    image: r4aks.azurecr.io/nsq-bench:v0
    imagePullPolicy: Always
    command: ["/go/bin/nsq.bench"]
    args: ["-runfor", "60s", "-nsqd-address", "localhost:4150", "-topic", "sub_bench_1", "-np", "10", "-ns", "0", "-nc", "1", "-flight", "200", "-batch-size","1"]
    resources:
      requests:
        cpu: "3"
        memory: "4Gi"
  initContainers:
    - name: bench
    image: r4aks.azurecr.io/nsq-bench:v0
    imagePullPolicy: Always
    command: ["/go/bin/nsq.bench"]
    args: ["-runfor", "60s", "-nsqd-address", "localhost:4150", "-topic", "sub_bench_1", "-np", "10", "-ns", "0", "-nc", "1", "-flight", "200", "-batch-size","1"]
    resources:
      requests:
        cpu: "3"
        memory: "4Gi"
  


  