apiVersion: batch/v1
kind: Job
metadata:
  name: bench-1
  labels:
    app: bench
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: bench
        image: r4aks.azurecr.io/nsq-bench:v0
        command:
	- /go/bin/nsq-bench 
	- -runfor
	- 60s
	- nsqd-address
	- nsq
	- -topic
	- sub_bench_1
	- -np
	- "10"
	- -ns
	- "10"
	- -nc
	- "1"
	- -flight
	- "1000"
        resources:
          requests:
            cpu: "3"
            memory: "4Gi"
