---
apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd-ex
  labels:
    app: nsq
spec:
  ports:
  - port: 4160
    targetPort: 4160
    name: tcp
  - port: 4161
    targetPort: 4161
    name: http
  selector:
    app: nsq
    component: nsqlookupd
  type: LoadBalancer 
---
apiVersion: v1
kind: Service
metadata:
  name: nsqd-ex
  labels:
    app: nsq
spec:
  ports:
  - port: 4150
    targetPort: 4150
    name: tcp
  - port: 4151
    targetPort: 4151
    name: http
  selector:
    app: nsq
    component: nsqd
  type: LoadBalancer 