
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-client
  labels:
    app: dispatcher-client
spec:
  replicas: 8
  selector:
    matchLabels:
      app: dispatcher-client
  template:
    metadata:
      labels:
        app: dispatcher-client
    spec:
      containers:
      - name: poc
        image: r4aks.azurecr.io/dispatcher.performance.poc:v5.1
        command: ["/go/bin/client"]
        args: ["-s", "dispatcher:50051", "-nsqd", "nsqd:4150", "-runfor", "60s", "-r", "10", "-c", "10","-snum", "10"] 
        ports:
        resources:
          requests:
            cpu: "3" 
            memory: "8Gi"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: password
        - name: REDIS_ADDR
          value: "telepathy.redis.cache.windows.net:6379"

        
