apiVersion: v1
kind: Service
metadata:
  name: dispatcher
  labels:
    app: dispatcher
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: dispatcher
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher-pprof
  labels:
    app: dispatcher-pprof
spec:
  ports:
  - port: 6060
    targetPort: 6060
  selector:
    app: dispatcher 
  type: LoadBalancer 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  labels:
    app: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - name: poc
        image: r4aks.azurecr.io/dispatcher.performance.poc:v1.9
        command: ["/go/bin/cmd"]
        args: ["-lookupd", "nsqlookupd-0.nsqlookupd:4161 nsqlookupd-1.nsqlookupd:4161 nsqlookupd-2.nsqlookupd:4161", "-p", "50051", "-b", "25000", "-maxinflight", "60000", "-poolsize", "1600", "-idlesize", "0"]
        ports:
        - containerPort: 50051
        - containerPort: 6060
        resources:
          requests:
            cpu: "14" 
            memory: "8Gi" 
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: password
        - name: REDIS_ADDR
          value: "telepathy.redis.cache.windows.net:6379"
          
