apiVersion: batch/v1
kind: Job
metadata:
  name: client3
  namespace: t
  labels:
    app: client3
spec:
    template:
      spec:
        restartPolicy: Never
        containers:
        - name: client3
          image: kuberegistry0.azurecr.io/t.poc:v3.4
          command: ["/go/bin/client"]
          args: ["-addr", "fe.t.svc.cluster.local:4001", "-q", "bootstrap.kafka.svc.cluster.local:9092", "-n", "500000",  "-t", "60"]
          resources:
            requests:
              cpu: "3"       
              memory: "4Gi"
        tolerations:
        - key: "CPU"
          operator: "Equal"
          value: "High"
          effect: "NoSchedule"
