


apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: t
  labels:
    app: worker
spec:
  replicas: 1400
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker1
        image: zkbpoc.azurecr.io/zkb-pull:v1
        command: ["/go/bin/worker"]
        args: ["-s", "dispatcher.t.svc.cluster.local:4002", "-cpu_tick", "1000","-c", "600", "-p", "3", "-req", "1025"]
        resources:
          requests:
            cpu: "0.5"       
