apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer
  namespace: telepathy
  labels:
    app: kafka-producer
spec:
    template:
      spec:
        restartPolicy: Never
        containers:
        - name: telepathy-poc-client
          image: kuberegistry0.azurecr.io/telepathy.poc.kafka:v1 
          command: ["/go/bin/kafka"]
          args: ["-n", "5000000", "-t","bench-kafka"]
          resources:
            requests:
              cpu: "3"       
              memory: "8Gi"
        tolerations:
        - key: "CPU"
          operator: "Equal"
          value: "High"
          effect: "NoSchedule"
