apiVersion: v1
kind: Pod
metadata:
  name: telepathy-client
  namespace: telepathy
  labels:
    app: telepathy-client
spec:
    containers:
    - name: telepathy-poc-client
      image: kuberegistry0.azurecr.io/telepathy.poc:v11
      command: ["/go/bin/client"]
      args: ["-addr", "telepathy-fe.telepathy.svc.cluster.local:4001", "-n", "100000", "-c", "5"]
       
