apiVersion: v1
kind: Pod
metadata:
  name: telepathy-client
  namespace: telepathy
  labels:
    app: telepathy-client
spec:
    containers:
    - name: telepathy-poc-client
      image: kuberegistry0.azurecr.io/telepathy.poc:v5
      command: ["/go/bin/client"]
      args: ["-FRONT_ADDR", "telepathy-fe-svc.telepathy.svc.cluster.local:4001", "-REQ_NUM", "10000", "-JOB_ID", "k8s-job-0"]
       