
apiVersion: v1
kind: Service
metadata:
  name: telepathy-cl-fe-svc
  namespace: telepathy
  labels:
    app: telepathy-cl-fe
spec:
  ports:
  - port: 6001
    targetPort: 6001
  selector:
    app: telepathy-cl-fe


        
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telepathy-cl-fe-statefulset
  namespace: telepathy
  labels:
    app: telepathy-cl-fe
spec:
  replicas: 16
  selector:
    matchLabels:
      app: telepathy-cl-fe
  template:
    metadata:
      labels:
        app: telepathy-cl-fe
    spec:
      containers:
      - name: telepathy-poc
        image: kuberegistry0.azurecr.io/telepathy.poc.client-fe:v1
        command: ["/go/bin/client_frontend"]
        args: ["-MQ_ADDR", "bootstrap.kafka.svc.cluster.local:9092", "-PORT", "6001", '-c', "2"]
        ports:
        - containerPort: 6001


