apiVersion: v1
kind: Pod
metadata:
  name: telepathy-client-cl
  namespace: telepathy
  labels:
    app: telepathy-client
spec:
  containers:
  - name: telepathy-poc-client
    image: kuberegistry0.azurecr.io/telepathy.poc.client-fe:v1
    command: ["/go/bin/client_frontend"]
    args: ["-FRONT_ADDR", "telepathy-cl-fe-svc.telepathy", "-REQ_NUM", "500000", "-serverNum", "16", "-PORT", "6001"]

