apiVersion: v1
kind: Service
metadata:
  name: telepathy-fe-svc
  namespace: telepathy
  labels:
    app: telepathy-fe
spec:
  ports:
  - port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    app: telepathy-fe
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telepathy-fe-deployment
  namespace: telepathy
  labels:
    app: telepathy-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telepathy-fe
  template:
    metadata:
      labels:
        app: telepathy-fe
    spec:
      containers:
      - name: telepathy-poc
        image: kuberegistry0.azurecr.io/telepathy.poc:v5
        command: ["/go/bin/frontend"]
        args: ["-MQ_ADDR", "bootstrap.kafka.svc.cluster.local:9092", "-PORT": "4001"]
        ports:
          - containerPort: 4001
  
        

        