apiVersion: v1
kind: Service
metadata:
  name: telepathy-fe
  namespace: telepathy
  labels:
    app: telepathy-fe
spec:
  ports:
  - port: 4001
    targetPort: 4001
  selector:
    app: telepathy-fe
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telepathy-fe
  namespace: telepathy
  labels:
    app: telepathy-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telepathy-fe
  template:
    metadata:
      labels:
        app: telepathy-fe
    spec:
      containers:
      - name: telepathy-poc
        image: kuberegistry0.azurecr.io/telepathy.poc:v2.2
        command: ["/go/bin/frontend"]
        args: ["-q", "bootstrap.kafka.svc.cluster.local:9092", "-p", "4001"]
        ports:
        - containerPort: 4001
        resources:
          requests:
            cpu: "3" 
        

        
