apiVersion: v1
kind: Service
metadata:
  name: telepathy-fe-svc
  labels:
    app: telepathy-fe
spec:
  ports:
  - port: 4520
    protocol: TCP
    targetPort: 4520
  selector:
    app: telepathy-fe
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telepathy-fe-deployment
  namespace: telepathy
  labels:
    app: telepathy-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telepathy-fe
  template:
    metadata:
      labels:
        app: telepathy-fe
    spec:
      containers:
      - name: telepathy-poc
        image: kuberegistry0.azurecr.io/telepathy.poc:v1
        command: ["/go/bin/frontend"]
        env:
          - name: MQ_ADDR
            value: 10.0.30.99:9092
          - name: PORT
            value: 4520
