apiVersion: v1
kind: Service
metadata:
  name: telepathy-wk-svc
  namespace: telepathy
  labels:
    app: telepathy-wk
spec:
  ports:
  - port: 4002
    protocol: TCP
    targetPort: 4002
  clusterIP: None
  selector:
    app: telepathy-wk
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telepathy-wk-stateful
  namespace: telepathy
  labels:
    app: telepathy-wk
spec:
  serviceName: "telepathy-wk"
  replicas: 5
  selector:
    matchLabels:
      app: telepathy-wk
  template:
    metadata:
      labels:
        app: telepathy-wk
    spec:
      containers:
      - name: telepathy-poc
        image: kuberegistry0.azurecr.io/telepathy.poc:v6
        command: ["/go/bin/worker"]
        args: ["-MQ_ADDR", "bootstrap.kafka.svc.cluster.local:9092", "-PORT", "4002"]
        ports:
        - containerPort: 4002


            
