apiVersion: v1
kind: Service
metadata:
  name: telepathy-wk
  namespace: telepathy
  labels:
    app: telepathy-wk
spec:
  ports:
  - port: 4002
    protocol: TCP
    targetPort: 4002
  clusterIP: None
  selector:
    app: telepathy-wk
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telepathy-wk
  namespace: telepathy
  labels:
    app: telepathy-wk
spec:
  serviceName: "telepathy-wk"
  replicas: 2
  selector:
    matchLabels:
      app: telepathy-wk
  template:
    metadata:
      labels:
        app: telepathy-wk
    spec:
      containers:
      - name: telepathy-poc
        image: kuberegistry0.azurecr.io/telepathy.poc:v3.1
        command: ["/go/bin/worker"]
        args: ["-q", "bootstrap.kafka.svc.cluster.local:9092", "-p", "4002"]
        ports:
        - containerPort: 4002
        resources:
          requests:
            cpu: "3"
            memory: "12Gi"
            
