apiVersion: v1
kind: Service
metadata:
  name: telepathy-wk-svc
  namespace: telepathy
  labels:
    app: telepathy-wk
spec:
  ports:
  - port: 4527
    protocol: TCP
    targetPort: 4527
  clusterIP: None
  selector:
    app: telepathy-wk
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telepathy-wk-stateful
  namespace: telepathy
  labels:
    app: telepathy-wk
spec:
  serviceName: "telepathy-wk"
  replicas: 5
  selector:
    matchLabels:
      app: telepathy-wk
  template:
    metadata:
      labels:
        app: telepathy-wk
    spec:
      containers:
      - name: telepathy-poc
        image: kuberegistry0.azurecr.io/telepathy.poc:v1
        command: ["/go/bin/worker"]
        env:
          - name: MQ_ADDR
            value: "bootstrap.kafka.svc.cluster.local:9092"
          - name: PORT
            value: "4527"


            
