
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-msg
  labels:
    app: pub-msg
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pub-msg
  template:
    metadata:
      labels:
        app: pub-msg
    spec:
      containers:
      - name: poc
        image: r4aks.azurecr.io/dispatcher.pulsar.poc:v1.2
        command: ["/go/bin/client"]
        args: ["-s", "dispatcher:50051", "-runfor", "30s", "-r", "10", "-c", "10","-nt", "10", "-p", "1"]
        ports:
        resources:
          requests:
            cpu: "3" 
            memory: "12Gi"        

        