apiVersion: v1
kind: Service
metadata:
  name: dispatcher
  labels:
    app: dispatcher
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: dispatcher
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher-pprof
  labels:
    app: dispatcher-pprof
spec:
  ports:
  - port: 6060
    targetPort: 6060
  selector:
    app: dispatcher 
  type: LoadBalancer 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  labels:
    app: dispatcher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - name: poc
        image: r4aks.azurecr.io/dispatcher.pulsar.poc:v1.2
        command: ["/go/bin/cmd"]
        args: [ "-p", "50051", "-pn", "1","-cn", "1"]
        ports:
        - containerPort: 50051
        - containerPort: 6060
        resources:
          requests:
            cpu: "14" 
            memory: "8Gi" 
    
          
