apiVersion: v1
kind: Service
metadata:
  name: dispatcher
  namespace: t
  labels:
    app: dispatcher
spec:
  ports:
  - port: 4002
    targetPort: 4002
  selector:
    app: dispatcher
---

apiVersion: v1
kind: Pod 
metadata:
  name: dispatcher
  namespace: t
  labels:
    app: dispatcher
spec:
    containers:
    - name: dispatcher
      image: kuberegistry0.azurecr.io/t.poc:v4.0.0
      command: ["/go/bin/dispatcher"]
      args: ["-n", "1000000", "-w", "100000", "-p", "4002", "-test_name", "svc", "-cpu_tick", "1000"]
      ports:
        - containerPort: 4002
      resources:
        requests:
          cpu: "3"       
          memory: "8Gi"
    tolerations:
    - key: "CPU"
      operator: "Equal"
      value: "High"
      effect: "NoSchedule"
