apiVersion: v1
kind: Service
metadata:
  name: dispatcher
  namespace: t
  labels:
    app: dispatcher
spec:
  ports:
  - port: 4002
    targetPort: 4002
  selector:
    app: dispatcher
---

apiVersion: v1
kind: Pod 
metadata:
  name: dispatcher
  namespace: t
  labels:
    app: dispatcher
spec:
    containers:
    - name: dispatcher
      image:  zkbpoc.azurecr.io/zkb-pull:v1   
      command: ["/go/bin/dispatcher"]
      args: ["-n", "100000", "-w", "160", "-p", "4002", "-cpu_tick", "1000"]
      ports:
        - containerPort: 4002
      resources:
        requests:
          cpu: "31"       
          memory: "4Gi"
    tolerations:
    - key: "CPU"
      operator: "Equal"
      value: "High"
      effect: "NoSchedule"
