apiVersion: batch/v1
kind: Job
metadata:
  name: worker
  namespace: t
  labels:
    app: worker
spec:
    template:
      spec:
        restartPolicy: Never
        containers:
        - name: worker
          image: kuberegistry0.azurecr.io/t.poc:v4.0.0
          command: ["/go/bin/worker"]
          args: ["-s", "dispatcher.t.svc.cluster.local:4002", "-cpu_tick", "1000", "-test_name": "wk"]
          resources:
            requests:
              cpu: "3"       
              memory: "4Gi"
        tolerations:
        - key: "CPU"
          operator: "Equal"
          value: "High"
          effect: "NoSchedule"
